name: "Change the gradle build parameters"
description: "This action will change the version code, version name and application id in build.gradle . "
inputs:
  gradlePath:
    description: "Gradle path to override version"
    required: true
    default: "app/build.gradle"
  versionCode:
    description: "The new version code"
    required: false
  versionName:
    description: "The new version name"
    required: false
  applicationId:
    description: "The application id to set"
    required: false
outputs:
  result: # id of output
    description: "Action Result"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: 'blue'
  icon: 'anchor'
